version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Setup locales
          command: |
            sudo sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen
            sudo locale-gen
      - run:
          name: Install Python dependencies in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run: 
          name: Run tests
          command: |
            . venv/bin/activate
            make test
